name: Bump release version
on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  build:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.merge_commit_sha }}
        fetch-depth: '0'
    - id: read-version
      uses: NiklasLehnfeld/flutter-version-number-action@main
      with:
          file-path: pubspec.yaml
    - uses: nick-invision/assert-action@v1
      with:
          expected: 0.0.1+1
          actual: ${{ steps.read-version.outputs.version-number }}

    # - name: version-tag
    #   id: tag
    #   uses: anothrNick/github-tag-action@master
    #   env:
    #       VERBOSE: true
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #       GIT_API_TAGGING: false
    #       WITH_V: true
    #
    # - name: automatic-draft-release
    #   uses: marvinpinto/action-automatic-releases@latest
    #   with:
    #       draft: false
    #       prerelease: false
    #       repo_token: ${{ secrets.GITHUB_TOKEN }}
    #       title: "${{ steps.tag.outputs.tag }}: ${{ github.repository }}"
    #       automatic_release_tag: ${{ steps.tag.outputs.new_tag }}
    #       generate_release_notes: true
    #       files: |
    #           README.md
    #
    - name: Changelog
      uses: Bullrich/generate-release-changelog@master
      id: Changelog
      env:
          REPO: ${{ github.repository }}
    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: ${{ steps.read-version.outputs.version-number }}
          release_name: Release ${{ steps.read-version.outputs.version-number }}
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          draft: false
          prerelease: false
